
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NominaAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AsientoContable
{

    public int id { get; set; }

    public System.DateTime Fecha { get; set; }

    public string Descripcion { get; set; }

    public int Auxiliar { get; set; }

    public int Cuentadb { get; set; }

    public int Cuentacr { get; set; }

    public double Monto { get; set; }

    public bool Contabilizado { get; set; }

    public string Estado { get; set; }



    public virtual Cuenta Cuenta { get; set; }

    public virtual Cuenta Cuenta1 { get; set; }

}

}
