//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientoContable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsientoContable()
        {
            this.Nomina = new HashSet<Nomina>();
        }
    
        public int id { get; set; }
        public Nullable<int> ContabilidadID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public int Auxiliar { get; set; }
        public int Cuentadb { get; set; }
        public int Cuentacr { get; set; }
        public double Monto { get; set; }
        public bool Contabilizado { get; set; }
        public string Estado { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Cuenta Cuenta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nomina> Nomina { get; set; }
    }
}
