
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NominaAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Empleado
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Empleado()
    {

        this.NominaResumen = new HashSet<NominaResumen>();

        this.Transaccion = new HashSet<Transaccion>();

    }


    public int id { get; set; }

    public string Cedula { get; set; }

    public string Nombre { get; set; }

    public double Salario { get; set; }

    public int DepartamentoID { get; set; }

    public int PuestoID { get; set; }

    public int TipoNominaID { get; set; }



    public virtual Departamento Departamento { get; set; }

    public virtual Puesto Puesto { get; set; }

    public virtual TipoNomina TipoNomina { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NominaResumen> NominaResumen { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Transaccion> Transaccion { get; set; }

}

}
