//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nomina()
        {
            this.NominaResumen = new HashSet<NominaResumen>();
        }
    
        public int id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Periodo { get; set; }
        public int TipoNominaID { get; set; }
        public bool Contabilizado { get; set; }
        public Nullable<int> AsientoContableID { get; set; }
    
        public virtual TipoNomina TipoNomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaResumen> NominaResumen { get; set; }
        public virtual AsientoContable AsientoContable { get; set; }
    }
}
