
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NominaAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class NominaResumen
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NominaResumen()
    {

        this.NominaDetalle = new HashSet<NominaDetalle>();

    }


    public int id { get; set; }

    public int NominaID { get; set; }

    public int EmpleadoID { get; set; }

    public double SueldoBruto { get; set; }

    public double SueldoDevengado { get; set; }



    public virtual Empleado Empleado { get; set; }

    public virtual Nomina Nomina { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NominaDetalle> NominaDetalle { get; set; }

}

}
