//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominaDetalle
    {
        public int id { get; set; }
        public int NominaResumenID { get; set; }
        public int TransaccionID { get; set; }
        public string Tipo { get; set; }
        public string Descripción { get; set; }
        public double Monto { get; set; }
    
        public virtual NominaResumen NominaResumen { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
