//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nomina()
        {
            this.NominaResumen = new HashSet<NominaResumen>();
        }
    
        public int id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Periodo { get; set; }
        public int TipoNominaID { get; set; }
        public bool Contabilizado { get; set; }
        public Nullable<int> AsientoContableID { get; set; }
    
        public virtual AsientoContable AsientoContable { get; set; }
        public virtual TipoNomina TipoNomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaResumen> NominaResumen { get; set; }
    }
}
