//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NominaResumen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NominaResumen()
        {
            this.NominaDetalle = new HashSet<NominaDetalle>();
        }
    
        public int id { get; set; }
        public int NominaID { get; set; }
        public int EmpleadoID { get; set; }
        public double SueldoBruto { get; set; }
        public double SueldoDevengado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Nomina Nomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaDetalle> NominaDetalle { get; set; }
    }
}
