
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NominaAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TipoNomina
{

    public int id { get; set; }

    public string TipoNomina1 { get; set; }

    public string Periodo { get; set; }

    public int EmpleadoID { get; set; }



    public virtual Empleado Empleado { get; set; }

}

}
