//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NominaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccion()
        {
            this.NominaDetalle = new HashSet<NominaDetalle>();
        }
    
        public int id { get; set; }
        public int EmpleadoID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> TipoIngresoID { get; set; }
        public Nullable<int> TipoDeduccionID { get; set; }
        public double Monto { get; set; }
        public bool Contabilizado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NominaDetalle> NominaDetalle { get; set; }
        public virtual TipoDeduccion TipoDeduccion { get; set; }
        public virtual TipoIngreso TipoIngreso { get; set; }
    }
}
