
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NominaAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Transaccion
{

    public int id { get; set; }

    public int EmpleadoID { get; set; }

    public System.DateTime fecha { get; set; }

    public bool IoD { get; set; }

    public string TipoIngreso { get; set; }

    public string TipoDeduccion { get; set; }

    public bool Contabilizado { get; set; }

    public double Monto { get; set; }



    public virtual Empleado Empleado { get; set; }

}

}
