//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Fin_Hibrido
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento_Contable
    {
        public int IdAsiento { get; set; }
        public string Descripcion { get; set; }
        public int IdEmpleado { get; set; }
        public string Cuenta { get; set; }
        public string TipoMovimiento { get; set; }
        public System.DateTime FechaAsiento { get; set; }
        public double MontoAsiento { get; set; }
        public bool Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
