//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Fin_Hibrido
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Asiento_Contable = new HashSet<Asiento_Contable>();
            this.RegistroTransacciones = new HashSet<RegistroTransacciones>();
        }
    
        public int IdEmpleado { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public double Salario { get; set; }
        public int IdDepartamento { get; set; }
        public int IdPuesto { get; set; }
        public int IdNomina { get; set; }
        [JsonIgnore]
        public virtual ICollection<Asiento_Contable> Asiento_Contable { get; set; }
        [JsonIgnore]
        public virtual Departamento Departamento { get; set; }
        [JsonIgnore]
        public virtual Nomina Nomina { get; set; }
        [JsonIgnore]
        public virtual Puesto Puesto { get; set; }
        [JsonIgnore]
        public virtual ICollection<RegistroTransacciones> RegistroTransacciones { get; set; }
    }
}
