//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Fin_Hibrido
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Empleado
    {
        public Empleado()
        {
            this.Asiento_Contable = new HashSet<Asiento_Contable>();
            this.RegistroTransacciones = new HashSet<RegistroTransacciones>();
        }
    
        public int IdEmpleado { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public double SalarioMensual { get; set; }
        public string Departamento { get; set; }
        public string Puesto { get; set; }
        public int IdNomina { get; set; }
    
        public virtual ICollection<Asiento_Contable> Asiento_Contable { get; set; }
        public virtual Nomina Nomina { get; set; }
        public virtual ICollection<RegistroTransacciones> RegistroTransacciones { get; set; }
    }
}
