//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Fin_Hibrido
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proyecto_Fin_HibridoEntities : DbContext
    {
        public Proyecto_Fin_HibridoEntities()
            : base("name=Proyecto_Fin_HibridoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Asiento_Contable> Asiento_Contable { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Nomina> Nomina { get; set; }
        public DbSet<RegistroTransacciones> RegistroTransacciones { get; set; }
        public DbSet<REL_TIPOS> REL_TIPOS { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TipoDeduccion> TipoDeduccion { get; set; }
        public DbSet<TipoIngreso> TipoIngreso { get; set; }
    }
}
