//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Fin_Hibrido
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroTransacciones
    {
        public int IdTransaccion { get; set; }
        public int IdEmpleado { get; set; }
        public int IdTipo { get; set; }
        public string TipoTransaccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Monto { get; set; }
        public bool Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual REL_TIPOS REL_TIPOS { get; set; }
    }
}
