//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Fin_Hibrido
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroTransacciones
    {
        public int IdTransaccion { get; set; }
        public int IdEmpleado { get; set; }
        public int IdTipo { get; set; }
        public string TipoTransaccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Monto { get; set; }
        public bool Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual REL_TIPOS REL_TIPOS { get; set; }
    }
}
