//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Fin_Hibrido
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_TIPOS
    {
        public REL_TIPOS()
        {
            this.RegistroTransacciones = new HashSet<RegistroTransacciones>();
        }
    
        public int IdTipo { get; set; }
        public Nullable<int> IdDeduccion { get; set; }
        public Nullable<int> IdIngreso { get; set; }
    
        public virtual ICollection<RegistroTransacciones> RegistroTransacciones { get; set; }
        public virtual TipoDeduccion TipoDeduccion { get; set; }
        public virtual TipoIngreso TipoIngreso { get; set; }
    }
}
