//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Fin_Hibrido
{
    using System;
    using System.Collections.Generic;
    
    public partial class REL_TIPOS
    {
        public REL_TIPOS()
        {
            this.RegistroTransacciones = new HashSet<RegistroTransacciones>();
        }
    
        public int IdTipo { get; set; }
        public Nullable<int> IdDeduccion { get; set; }
        public Nullable<int> IdIngreso { get; set; }
    
        public virtual ICollection<RegistroTransacciones> RegistroTransacciones { get; set; }
        public virtual TipoDeduccion TipoDeduccion { get; set; }
        public virtual TipoIngreso TipoIngreso { get; set; }
    }
}
