//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Fin_Hibrido
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class TipoDeduccion
    {
        public TipoDeduccion()
        {
            this.REL_TIPOS = new HashSet<REL_TIPOS>();
        }
    
        public int IdDeduccion { get; set; }
        public string Nombre { get; set; }
        public bool DependeSalario { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<REL_TIPOS> REL_TIPOS { get; set; }
    }
}
