//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Fin_Hibrido
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class TipoIngreso
    {
        public TipoIngreso()
        {
            this.REL_TIPOS = new HashSet<REL_TIPOS>();
        }

        [JsonProperty(PropertyName = "id")]
        public int IdIngreso { get; set; }
        public string Nombre { get; set; }
        public bool DependeSalario { get; set; }
        public bool Estado { get; set; }
        [JsonIgnore]
        public virtual ICollection<REL_TIPOS> REL_TIPOS { get; set; }
    }
}
